
var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/coffee.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="speedy service";
lay.appendChild(word);var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/whitecom.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="crisp icons";
lay.appendChild(word);var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/wall.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="detail-oriented";
lay.appendChild(word);var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/purp.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="customer friendly";
lay.appendChild(word);var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/pole.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="dynamic layouts";
lay.appendChild(word);var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/edge.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="responsive";
lay.appendChild(word);var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/coftab.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="affordable";
lay.appendChild(word);var con = document.getElementById("thumb-container clearfix");
var face = document.createElement("div");
face.className="thumb-unit";
face.style.backgroundImage="url(./img/blackdude.jpg)";
con.appendChild(face);
var lay = document.createElement("div");
lay.className="thumb-overlay";
face.appendChild(lay);
var word = document.createElement("a");
word.setAttribute("href","https://www.youtube.com/");
word.innerHTML="professional";
lay.appendChild(word);